### ISSUE TITLE
Image blocking context menu entry intermittently doesn't work.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/adblock-latitude#29]
https://forum.palemoon.org/viewtopic.php?f=46&t=23642

> Just in case, it might be helpful for you to know that the breaking change was [deae241](https://github.com/MoonchildProductions/UXP/commit/deae241f5e3db8f9b86b98933291b9a30e28db22).

So, we might need a change to the extension JS using `asyncOpen2()` instead of `asyncOpen()`?

**Comment by JustOff** [comment]
As I understand it, the reason is that after [[deae241]](https://github.com/MoonchildProductions/UXP/commit/deae241f5e3db8f9b86b98933291b9a30e28db22) was applied [nsIContentPolicy#shouldLoad()](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/nsIContentPolicy#shouldLoad()) is no longer called for images, while it's required to collect node data using [RequestNotifier.addNodeData()](https://github.com/MoonchildProductions/adblock-latitude/blob/34754715ec0887efe1ded2533e8b72fd93e9bc61/src/lib/child/contentPolicy.js#L94) using [processPolicyResponse()](https://github.com/MoonchildProductions/adblock-latitude/blob/34754715ec0887efe1ded2533e8b72fd93e9bc61/src/lib/child/contentPolicy.js#L74), which is called from [shouldAllow()](https://github.com/MoonchildProductions/adblock-latitude/blob/34754715ec0887efe1ded2533e8b72fd93e9bc61/src/lib/child/contentPolicy.js#L120), which is called from [PolicyImplementation.shouldLoad()](https://github.com/MoonchildProductions/adblock-latitude/blob/34754715ec0887efe1ded2533e8b72fd93e9bc61/src/lib/child/contentPolicy.js#L261).

**Comment by JustOff** [comment]
@mattatobin, btw, ABPrime has the same issue.

**Comment by wolfbeast** [comment]
So, was the solution there incomplete? And has this been broken since 28.7.0 and should be backed out, or is there a simple solution?

**Comment by JustOff** [comment]
I can't say for sure it's incomplete, since the image blocking itself works just fine and no other side effects have been reported since last August. At the same time, I don't see a simple solution to this issue either.

Perhaps @win7-7 can also take a look at this?
